name: Build and Deploy FE

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18" # Specify your Node.js version here

      - name: Install dependencies
        run: npm install
        working-directory: FE

      - name: Build
        run: npm run build
        working-directory: FE

      - name: Archive build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: built-app
          path: FE/dist

      - name: Deploy to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DEPLOY_SERVER }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          source: "FE/dist/fe/"
          target: "/var/www/html"
          strip_components: 3
