name: Build and Deploy BE

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '18' # Set this to your project's Node.js version
  
    - name: Deploy to Server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.DEPLOY_SERVER }}
        username: ${{ secrets.DEPLOY_USER }}
        key: ${{ secrets.DEPLOY_KEY }}
        port: 22
        source: "BE/src/"
        target: "/home/${{ secrets.DEPLOY_USER }}/app"

    - name: Restart the application using PM2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEPLOY_SERVER }}
        username: ${{ secrets.DEPLOY_USER }}
        key: ${{ secrets.DEPLOY_KEY }}
        port: 22
        script: pm2 restart all