name: Build and Deploy FE

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'  # Specify your Node.js version here

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Archive build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: built-app
        path: dist

    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@v2.1.5
      env:
        SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
        ARGS: "-avz --delete"
        SOURCE: "path/to/your/build/directory/"
        TARGET: "${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_SERVER }}:/var/www/html"